HIS_V1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('register.urls')),
    path('', include("django.contrib.auth.urls")),
    path('', include("HIS_app.urls")),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

HIS_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("about_us/", views.about_us, name="about_us"),
    path("doctors/", views.doctors, name="doctors"),
    path("patients/", views.patients, name="patients"),
    path("medical_history/", views.medical_history, name="medical_history"),
    path("doctor/<int:doctor_id>/edit/", views.edit_doctor, name="edit_doctor"),
    path("doctor/<int:doctor_id>/delete/", views.delete_doctor, name="delete_doctor"),
    path("patient/<int:patient_id>/", views.patient_details, name="patient"),
    path("patient/<int:patient_id>/edit/", views.edit_patient, name="edit_patient"),
    path("patient/<int:patient_id>/delete/", views.delete_patient, name="delete_patient"),
    path("patient/<int:patient_id>/approve/", views.approve_patient, name="approve_patient"),
    path("patient_history/<int:patient_id>/", views.patient_history, name="patient_history"),
    path("appointments/", views.appointments, name="appointments"),
    path("appointment/<int:appt_id>/delete/", views.delete_appt, name="delete_appt"),
    path("appointment/<int:appt_id>/cancel/", views.cancel_appt, name="cancel_appt"),
    path("appointment/<int:appt_id>/approve/", views.approve_appt, name="approve_appt"),
    path("appointment/<int:appt_id>/update/", views.update_appt, name="update_appt"),
    path("appointment/<int:appt_id>/edit/", views.edit_appt, name="edit_appt"),
    path("book_appointment/", views.book_appointment, name="book_appointment"),
    path("my_appointments/", views.my_appointments, name="my_appointments"),
    path("my_history/", views.my_history, name="my_history"),
    ]

HIS_app/forms.py
from django import forms
from .models import Patient, Doctor, Appointment, MedicalHistory, Specialization
from phonenumber_field.formfields import PhoneNumberField
from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput
from django.contrib.auth.models import User

class BookAppointmentForm(forms.Form):

    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "First Name*", 'type': "text", 'aria-label': "full_name", 'aria-describedby': "basic-addon2", "font-size": "12px"}), required=True)
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Last Name*", 'type': "text", 'aria-label': "full_name", 'aria-describedby': "basic-addon2", "font-size": "12px"}), required=True)
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Email Address (john@example.com)*", 'type': "email", 'aria-label': "email", 'aria-describedby': "basic-addon2", "font-size": "12px"}), required=False)
    number = PhoneNumberField(region="ET", widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Mobile Number (eg. 0912345678, 0116262728)*", 'type': "tel", 'aria-label': "phone", 'aria-describedby': "basic-addon2", "font-size": "12px"}), required=True)
    specialization = forms.ModelChoiceField(queryset=Specialization.objects.all(), widget=forms.Select(
        attrs={'class': "form-control", 'placeholder': "Campaign Title", 'label': 'test', 'type': "text", 'aria-label': "Choose Specialization", 'aria-describedby': "basic-addon2"}), label="Specializations", empty_label='Select Specialization')
    message = forms.CharField(widget=forms.Textarea(
        attrs={'class': "form-control", 'placeholder': "Symptoms/Reasons for Booking*", 'type': "text", 'aria-label': "message", 'aria-describedby': "basic-addon2", "font-size": "15px", 'rows': 10, 'cols': 15}), required=True)


class ContactForm(forms.Form):
    full_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Name", 'type': "text", 'aria-label': "full_name", 'aria-describedby': "basic-addon2", "font-size": "12px"}), required=True)
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Email Address", 'type': "email", 'aria-label': "email", 'aria-describedby': "basic-addon2", "font-size": "12px"}), required=True)
    phone = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Mobile Number", 'type': "tel", 'aria-label': "phone", 'aria-describedby': "basic-addon2", "font-size": "12px"}), required=False)
    message = forms.CharField(widget=forms.Textarea(
        attrs={'class': "form-control", 'placeholder': "Message", 'type': "text", 'aria-label': "message", 'aria-describedby': "basic-addon2", "font-size": "15px", 'rows': 10, 'cols': 15}), required=True)

class SearchForm(forms.Form):
    search_query = forms.CharField(widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': "Type Patient name or phone number(eg. 9xxxxxxxx, 11xxxxxxx)", 'type': "text", 'aria-label': "message", 'aria-describedby': "basic-addon2", "font-size": "15px"}), required=False)

class CreateNewPatient(forms.Form):
    pass

class CreateNewDoctor(forms.Form):
    pass

# For Admin Only
class UpdateApptForm(forms.ModelForm):
    specialization = forms.ModelChoiceField(queryset=Specialization.objects.all(), widget=forms.Select(
        attrs={'class': "form-control", 'placeholder': "Campaign Title", 'label': 'test', 'type': "text", 'aria-label': "Choose Specialization", 'aria-describedby': "basic-addon2"}), label="Specializations", empty_label='Select Specialization')
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all(), widget=forms.Select(
        attrs={'class': "form-control", 'placeholder': "Campaign Title", 'label': 'test', 'type': "text", 'aria-label': "Assign a  Doctor", 'aria-describedby': "basic-addon2"}), label="Doctors", empty_label='Assign a Doctor')
    class Meta:
        model = Appointment
        fields = ('patient', 'doctor', 'appointment_date', 'appointment_time','patient_message','specialization', 'is_approved', 'is_met')
        labels = {
            'patient': 'Patient',
            'doctor': 'Doctor',
            'appointment_date': 'AP_date',
            'appointment_time': 'AP_time',
            'patient_message': 'Patient Message',
            'specialization': 'Specialization',
            'is_approved': 'Approved',
            'is_met': 'Met',
        }
        widgets = {
            'patient': forms.TextInput(attrs={'class': "form-control", 'placeholder': "Patient name", 'type': "text", 'aria-label': "Type Patient Name Here", 'aria-describedby': "basic-addon2", 'readonly': 'readonly'}),
            'patient_message': forms.Textarea(
                attrs={'class': "form-control", 'placeholder': "Symptoms/Reasons for Booking*", 'type': "text", 'aria-label': "message", 'aria-describedby': "basic-addon2", "font-size": "15px", 'rows': 10, 'cols': 15}),
            "appointment_date": DatePickerInput(attrs={"class": "input-group date"},
                                          options={
                "format": "YYYY-MM-DD",
                "showTodayButton": True}),
            "appointment_time": TimePickerInput(),

        }


# For Patient Only
class EditApptForm(forms.ModelForm):
    specialization = forms.ModelChoiceField(queryset=Specialization.objects.all(), widget=forms.Select(
        attrs={'class': "form-control", 'placeholder': "Campaign Title", 'label': 'test', 'type': "text", 'aria-label': "Choose Specialization", 'aria-describedby': "basic-addon2"}), label="Specializations", empty_label='Select Specialization')
    class Meta:
        model = Appointment
        fields = ('first_name', 'last_name', 'patient_message','specialization')
        labels = {
            'patient_message': 'Describe Your Symptoms/Message',
            'first_name': 'First Name of Patient',
            'last_name': 'Last Name of Patient',
        }
        widgets = {
            'patient_message': forms.Textarea(
                attrs={'class': "form-control", 'placeholder': "Symptoms/Reasons for Booking*", 'type': "text", 'aria-label': "message", 'aria-describedby': "basic-addon2", "font-size": "15px", 'rows': 10, 'cols': 15}),
            'first_name': forms.TextInput(
                attrs={'class': "form-control", 'placeholder': "First Name*", 'type': "text", 'aria-label': "full_name", 'aria-describedby': "basic-addon2", "font-size": "12px"}),
            'last_name': forms.TextInput(
                attrs={'class': "form-control", 'placeholder': "Last Name*", 'type': "text", 'aria-label': "full_name", 'aria-describedby': "basic-addon2", "font-size": "12px"})
        }



# For Admin Only
class EditPatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['user', 'contact_number', 'date_of_birth', 'address', 'ec_Name', 'ec_Phone_Number', 'ec_Address', 'is_approved', 'is_discharged']

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)


    def __init__(self, *args, **kwargs):
        super(EditPatientForm, self).__init__(*args, **kwargs)
        # Disable the user field.
        self.fields['user'].disabled = True

        # Set initial values for first_name and last_name fields
        if self.instance and self.instance.user:
            user = self.instance.user
            self.initial['first_name'] = user.first_name
            self.initial['last_name'] = user.last_name

    def clean_contact_number(self):
        contact_number = self.cleaned_data['contact_number']
        # TODO: validation logic for contact number goes here
        return contact_number

    def clean_ec_Phone_Number(self):
        ec_phone_number = self.cleaned_data['ec_Phone_Number']
        # TODO: validation logic for emergency contact phone number goes here
        return ec_phone_number

class AddHistoryForm(forms.ModelForm):
    class Meta:
        model = MedicalHistory
        fields = ["height", "weight", "age", "blood_type", "history"]

class EditDoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['user', 'contact_number', 'address', 'specialization', 'is_doctor']

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)


    def __init__(self, *args, **kwargs):
        super(EditDoctorForm, self).__init__(*args, **kwargs)
        # Disable the user field.
        self.fields['user'].disabled = True

        # Set initial values for first_name and last_name fields
        if self.instance and self.instance.user:
            user = self.instance.user
            self.initial['first_name'] = user.first_name
            self.initial['last_name'] = user.last_name

    def clean_contact_number(self):
        contact_number = self.cleaned_data['contact_number']
        # TODO: validation logic for contact number goes here
        return contact_number

HIS_app/templates/HIS_app/book_appointment.html
{% extends 'HIS_app/dashboard_patient_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Dashboard[Patient] {% endblock %}

{% block header %}
Dashboard[{{user.first_name}}]
{% endblock %}

{% block content %}
<br>
<br>
<div class="card mb-4" style="background:#222428; color:grey; box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22); border-radius: 20px; ">
  <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Book Appointments Here
  </div>
  <div class="card-body">
        <div class="form-wrap" id="appt_form" style="background-color:cadetblue">
        <!-- insert form here -->
            <form method="POST" class="form-group appt_form">
                {% csrf_token %}
                {{appt_form|crispy}}
                <br>
                <button name="appt_submit" type="submit" class="btn btn-lg w-100 btn-outline-light" style="display:inline; margin: 0;">Book Appointment</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

HIS_app/templates/HIS_app/contact.html
{% extends "HIS_app/base.html" %}
{% load static %}

{% block title %}
Get In Touch! - M-ini.me
{% endblock %}

{% load crispy_forms_tags %}

{% block header %}Get In Touch!{% endblock %}
{% block content %}
<style>
    h1, p, label {
        color: white !important;
    }
    .bi {
        background-color: #c47d6a;
    }
  .flex-shrink-0 {
    background-color: cadetblue;
    }
    html {
        background-color: cadetblue;
    }
</style>
    <!-- Page content-->
    <section class="py-5">
        <div class="container px-5">
        {% if message_name %}
            <center>
                <br>
                <h1>{{message_name|safe}}</h1>
                <p>We Recieved Your Email and Will Get Back To You Shortly!</p>
                <br>
                <a href="/" class="btn btn-lg btn-outline-dark" style="color:cyan; background:black"><i class="fa fa-house" style="color:cyan; background:black"> </i> Go Back</a>
            </center>

        {% else %}
                <!-- Contact form-->
                <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5" style="background-color:cadetblue !important">
                    <div class="text-center mb-5">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3" style="background-color:#c47d6a !important"><i class="bi bi-envelope"></i></div>
                        <h1 class="fw-bolder">Get in touch</h1>
                        <p class="lead fw-normal text-muted mb-0" style="color:white !important">We'd love to hear from you</p>
                    </div>
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-8 col-xl-6">

                            <form method="POST">
                                {% csrf_token %}
                                {{form|crispy}}
                                <br>
                                <center>
                                <input class="btn btn-primary btn-lg" type="submit" value="Send Message" style="color:white; background:#c47d6a">
                                </center>
                            </form>
                        </div>
                    </div>
                </div>
        {% endif %}
            </div>
    </section>

{% endblock %}

HIS_app/templates/HIS_app/dashboard_base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <!-- Author -->
        <meta name="author" content="Eskias Yilma" />
        <meta name="color-scheme" content="dark" />
        {% if request.path == "/" %}
        <title>Dashboard - Clinicare.io | Lorem ipsum dolor sit amet</title>
        {% else %}
        <title>
        {% with name=request.path %} {{name|title}} {% endwith %} - Clinicare.io | Lorem ipsum dolor sit amet, consectetur adipiscing elit.</title>
        {% endif %}
        <!-- Description -->
        <meta name="description" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae hendrerit velit, in eleifend nisi. Donec sodales, tortor in cursus congue." />
        <!-- Keywords -->
        <meta name="keywords" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae hendrerit velit, in eleifend nisi. Donec sodales, tortor in cursus congue." />
        <!-- Canonical -->
        <link rel="canonical" href="https://clinicare.m-ini.me{{request.path}}">
        <!-- Home Link -->
        <link rel="home" href="{% url 'home' %}">
        <!-- Color Scheme -->
        <meta name="color-scheme" content="dark" />
        <!-- Favicon-->
        <link rel="shortcut-icon" type="image/png" href="{% static 'HIS_app/MyClinicare.io1.png' %}" type="image/x-icon" />
        <link rel="icon" type="image/png" href="{% static 'HIS_app/MyClinicare.io1.png' %}" />
        <link rel="apple-touch-icon" type="image/png" href="{% static 'HIS_app/MyClinicare.io1.png' %}" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" type="text/javascript"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'HIS_app/dashboard.css' %}">
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/6.6.6/css/flag-icons.min.css" integrity="sha512-uvXdJud8WaOlQFjlz9B15Yy2Au/bMAvz79F7Xa6OakCl2jvQPdHD0hb3dEqZRdSwG4/sknePXlE7GiarwA/9Wg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <script src="https://secure.exportkit.com/cdn/js/ek_googlefonts.js?v=6"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Ubuntu">
        <style>
          body {
            font-family: 'Ubuntu', serif !important;
            font-size: 15px !important;
          }
        </style>

        {% block styles %}{% endblock %}
    </head>
    <body class="sb-nav-fixed" style="font-family: Ubuntu;font-size: 13px;">
<style>
    h3 {
        color: white !important;
    }
    h1.mt-4.text-center {
        color: white !important;
    }
    .row {
         text-align:center;
    }
    #content-container { display: block; position: relative; width: 269px; width: 269px; height: 435px; overflow: hidden; display: block;  margin-left: auto; margin-right: auto;  }
    #page_frame_1_ek1 {
        top: 0px;
        left: 0px;
        width: 269px;
        height: 435px;
    }
    #_bg__frame_1_ek2 {
        top: 0px;
        left: 0px;
        width: 269px;
        height: 435px;
        background:rgba(255,255,255,1);
    }
    #rectangle_1 {
        top: 0px;
        left: 0px;
        width: 269px;
        height: 162px;
        background:rgba(245.44,169.76,169.76,1);
    }
    #ellipse_1 {
        top: 112px;
        left: 85px;
        width: 118px;
        height: 118px;
        -ms-border-radius: 50px / 50px;
        -o-border-radius: 50px / 50px;
        -moz-border-radius: 50px / 50px;
        -webkit-border-radius: 50px / 50px;
        border-radius: 50px / 50px;
        border: 9px solid #ffffff;
        background:rgba(217,217,217,1);
    }
    .card {
        box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);
        padding: 5px;
        border-color: aqua;
        background-color: #c2d5cb !important;
        border-radius: 15px;
    }
    #id_url_text {
        font-size: 12px;
    }
    #id_search_query {
        width: 100%;
        height: auto;
    }
    /*TABLE CSS*/
  .table {
    --bs-table-bg: rgba(0,0,0,0);
    --bs-table-striped-color: #6C7293;
    --bs-table-striped-bg: rgba(0,0,0,0.05);
    --bs-table-active-color: #6C7293;
    --bs-table-active-bg: rgba(0,0,0,0.1);
    --bs-table-hover-color: #6C7293;
    --bs-table-hover-bg: rgba(0,0,0,0.075);
    width: 100%;
    margin-bottom: 1rem;
    color: #6C7293;
    vertical-align: top;
    border-color: #000;
    }

    .image-popup {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.7);
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }

    .image-popup img {
      border-radius: 10px;
      max-width: 80%;
      max-height: 80%;
      object-fit: contain;
    }

    .image-popup a {
      color: white;
      font-size: 20px;
      margin-top: 20px;
      text-decoration: none;
      border-bottom: 1px solid white;
    }
    .fa-qrcode {
      border: 1px solid #F5F5F5;
      padding: 5px;
      border-color: grey;
      border-radius: 5px;
      color: green;
      font-size: 15px;
    }

    .dataTable-container {
      text-align-last: center;
      border-radius: 15px;
    }
    .card-body {
        background-color: cadetblue;
        border-radius: 15px;
    }
    .container {
        background-color: cadetblue;
        border-radius: 15px;
    }
    .card-header {
        font-size: 20px !important;
        color: #ed600b !important;
        background-color: white;
        border-radius: 15px !important;
    }
    .card-footer {
        border-radius: 15px !important;
    }
    table, td{
        background-color: mintcream;
        border-radius: 15px;
    }
    main {
        background-color: #599496 !important;
    }

    .dataTable-selector {
        background-color: white !important;
    }
    label {
        color: white;
    }
    .dataTable-info {
        color: white;
    }
</style>

        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark" style="box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22);">
            <!-- Navbar Brand-->
            <span class="fa fa-linux"></span><a class="navbar-brand ps-3" href="/">Clinicare.io</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" style="background:#222428; color:grey">

            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="/edit_profile">My Profile</a></li>
                        <li><a class="dropdown-item" href="/recent_activity">Activity Log</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="/logout">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                {% block navbar %}

                {% endblock %}
            </div>
            <div id="layoutSidenav_content" style="background:#222428">
                <main style="background:#222428">
                    <div class="container-fluid px-4">
                        <h1 class="mt-4 text-center" style="color:#8f8d8d">{% block header %}{% endblock %}</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">{{header}}</li>
                        </ol>
                        {% if messages %}
                            {% for msg in messages %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                  {{ msg }}
                                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            {% endfor %}
                        {% endif %}
                        {% block content %}

                        {% endblock %}
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto" style="background-color:#343a40">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Clinicare.io 2023. All Rights Reserved.</div>
                            <div>
                                <a href="/privacy">Privacy</a>
                                &middot;
                                <a href="/terms">Terms</a>
                                &middot;
                                <a href="/contact">Contact</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'HIS_app/dashboard.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@5" type="text/javascript"></script>
        <script>
            window.addEventListener('DOMContentLoaded', event => {
                const datatablesSimple = document.getElementById('datatablesSimple');
                if (datatablesSimple) {
                    new simpleDatatables.DataTable(datatablesSimple);
                }
            });
        </script>
    </body>
</html>

HIS_app/templates/HIS_app/dashboard_doctor.html
{% extends 'HIS_app/dashboard_base.html' %}
{% load static %}
{% block title %} Dashboard[Doctor] {% endblock %}

{% block header %}
Dashboard[Doctor]
{% endblock %}

{% block content %}
<h1>Doctor</h1>
{% endblock %}

HIS_app/templates/HIS_app/medical_history.html
{% extends "HIS_app/dashboard_admin.html" %}
<!-- Load Static -->
{% load static %}
<!-- Load custom template filters -->
{% block title %} Patient History {% endblock %}

{% block header %}
Manage Patient History
{% endblock %}


{% block content %}
<style>
  .table {
    --bs-table-bg: rgba(0,0,0,0);
    --bs-table-striped-color: #6C7293;
    --bs-table-striped-bg: rgba(0,0,0,0.05);
    --bs-table-active-color: #6C7293;
    --bs-table-active-bg: rgba(0,0,0,0.1);
    --bs-table-hover-color: #6C7293;
    --bs-table-hover-bg: rgba(0,0,0,0.075);
    width: 100%;
    margin-bottom: 1rem;
    color: #6C7293;
    vertical-align: top;
    border-color: #000;
}

.image-popup {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.image-popup img {
  border-radius: 10px;
  max-width: 80%;
  max-height: 80%;
  object-fit: contain;
}

.image-popup a {
  color: white;
  font-size: 20px;
  margin-top: 20px;
  text-decoration: none;
  border-bottom: 1px solid white;
}
.fa-qrcode {
  border: 1px solid #F5F5F5;
  padding: 5px;
  border-color: grey;
  border-radius: 5px;
  color: green;
  font-size: 15px;
}

.dataTable-container {
  text-align-last: center;
}

</style>



<div class="card mb-4" style="background:#222428; color:grey; box-shadow: 0 19px 38px rgba(0,0,0,0.30), 0 15px 12px rgba(0,0,0,0.22); border-radius: 20px; ">
  <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Manage Patient History Here
  </div>
  <div class="card-body">

    <table id="datatablesSimple" class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <!-- TODO Add DOctor / Diagnosed By-->
          <th scope="col">Patient</th>
          <th scope="col">Height</th>
          <th scope="col">Weight</th>
          <th scope="col">Age</th>
          <th scope="col">History</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <!-- TODO Add DOctor / Diagnosed By-->
          <th scope="col">Patient</th>
          <th scope="col">Height</th>
          <th scope="col">Weight</th>
          <th scope="col">Age</th>
          <th scope="col">History</th>
        </tr>
      </tfoot>
      <tbody>
        {% for i in history %}
            <tr>
              <td>{{forloop.counter}}</td>
              <td>{{i.date}}</td>
              <td>{{i.patient.user.first_name}} {{i.patient.user.last_name}}</td>
              <td>{{i.height}}</td>
              <td>{{i.weight}}</td>
              <td>{{i.age}}</td>
              <td>{{i.history}}</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>

{% endblock %}